// Writes contracts/test/fixtures/zk/signals.json: real proofs for the contract tests.
// Development identities only (small fixed secrets).
//
//   npm run fixture -w @arl/zk

import { mkdirSync, writeFileSync } from "node:fs";

import { loadCircuit } from "./circuit.ts";
import { commitment, createGroup, proveSignal, signalInputs } from "./index.ts";

const circuit = loadCircuit();
const secrets = [11n, 22n, 33n, 44n, 55n];
const group = createGroup(secrets.map(commitment));

const s = (v: bigint) => v.toString();
async function signal(secret: bigint, scope: bigint, message: bigint) {
  const p = await proveSignal(circuit, signalInputs(secret, group, scope, message));
  return {
    scope: s(p.scope),
    message: s(p.message),
    root: s(p.root),
    nullifier: s(p.nullifier),
    proof: p.proof,
  };
}

const fixture = {
  note: "Generated by packages/zk (npm run fixture -w @arl/zk). Development identities only.",
  commitments: secrets.map((x) => s(commitment(x))),
  root: s(group.root),
  // Member 2 votes 1 in poll 7; member 2 again in poll 8; member 4 votes 2 in poll 7.
  signals: [await signal(22n, 7n, 1n), await signal(22n, 8n, 1n), await signal(44n, 7n, 2n)],
};
const dir = new URL("../../../contracts/test/fixtures/zk/", import.meta.url);
mkdirSync(dir, { recursive: true });
writeFileSync(new URL("signals.json", dir), JSON.stringify(fixture, null, 2) + "\n");
process.stdout.write("wrote contracts/test/fixtures/zk/signals.json\n");
