// Writes contracts/deployedContracts.ts from the Foundry build and the local fixture deployment
// (contracts/script/DevDapp.s.sol). Same output shape as Scaffold-ETH 2's generator (MIT).
//
//   node scripts/generate-contracts.ts [--check] [deployment.json]
//
// --check compares instead of writing, and fails if the committed file is out of date.
//
// The fixture is deployed by Anvil development account 0 on a fresh chain, so the addresses are
// the same on every run; CI regenerates the file and fails if it differs from the committed one.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsDir = join(here, "..", "..", "..", "contracts");
const args = process.argv.slice(2);
const check = args.includes("--check");
const deploymentPath =
  args.find((a) => a !== "--check") ??
  join(contractsDir, "deploy", "deployments", "31337-dapp.json");
const outPath = join(here, "..", "contracts", "deployedContracts.ts");

interface Deployment {
  chainId: number;
  token: string;
  vesting: string;
  staking: string;
}

/** Compares content, not layout (the committed file is formatted by prettier). */
function normalise(text: string): string {
  return text
    .replace(/\s+/g, "")
    .replace(/,([}\]])/g, "$1")
    .replace(/"(\w+)":/g, "$1:");
}

const deployment = JSON.parse(readFileSync(deploymentPath, "utf8")) as Deployment;
if (deployment.chainId !== 31_337)
  throw new Error(`fixture chain ${String(deployment.chainId)} is not local Anvil`);

const abi = (name: string): unknown =>
  (
    JSON.parse(readFileSync(join(contractsDir, "out", `${name}.sol`, `${name}.json`), "utf8")) as {
      abi: unknown;
    }
  ).abi;

const zk = JSON.parse(readFileSync(join(dirname(deploymentPath), "31337-zk.json"), "utf8")) as {
  signal: string;
};

const contracts = {
  ARLAnonymousSignal: { address: zk.signal, abi: abi("ARLAnonymousSignal") },
  ARLToken: { address: deployment.token, abi: abi("ARLToken") },
  ARLVestingWallet: { address: deployment.vesting, abi: abi("ARLVestingWallet") },
  ARLStakingRewards: { address: deployment.staking, abi: abi("ARLStakingRewards") },
};

const source = `/**
 * Generated by scripts/generate-contracts.ts from the Foundry build and the local fixture
 * (contracts/script/DevDapp.s.sol). Do not edit by hand.
 */
import type { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  ${String(deployment.chainId)}: ${JSON.stringify(contracts, null, 2).replace(/\n/g, "\n  ")},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;
if (check) {
  const current = readFileSync(outPath, "utf8");
  if (normalise(current) !== normalise(source)) {
    console.error(`${outPath} is out of date: run npm run contracts after a local deployment`);
    process.exit(1);
  }
  console.log("deployedContracts.ts matches the local deployment");
} else {
  writeFileSync(outPath, source);
  console.log(`wrote ${outPath} (format it with prettier)`);
}
