// Writes lib/deployArtifacts.ts: the keccak-256 of the creation code of each contract the
// Deploy screen may create, from the Foundry build. The screen refuses a contract creation whose
// code (the first `creationSize` bytes, before the constructor arguments) does not hash to one
// of these.
//
//   node scripts/generate-deploy-artifacts.ts [--check]
//
// --check compares instead of writing, and fails if the committed file is out of date.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { keccak256, type Hex } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const contractsDir = join(here, "..", "..", "..", "contracts");
const outPath = join(here, "..", "lib", "deployArtifacts.ts");
const check = process.argv.includes("--check");

const NAMES = ["ARLVestingWallet", "ARLTimelock", "ARLToken"] as const;

interface ForgeArtifact {
  bytecode: { object: Hex };
  abi: { type: string; inputs?: { type: string; components?: unknown[] }[] }[];
}

const entries = NAMES.map((name) => {
  const a = JSON.parse(
    readFileSync(join(contractsDir, "out", `${name}.sol`, `${name}.json`), "utf8"),
  ) as ForgeArtifact;
  const ctor = a.abi.find((x) => x.type === "constructor");
  return [
    name,
    {
      creationHash: keccak256(a.bytecode.object),
      creationSize: (a.bytecode.object.length - 2) / 2,
      constructorInputs: ctor?.inputs ?? [],
    },
  ];
});

const source = `/**
 * Generated by scripts/generate-deploy-artifacts.ts from the Foundry build. Do not edit by hand.
 */
export const DEPLOY_ARTIFACTS = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const;
`;

const normalise = (t: string) =>
  t
    .replace(/\s+/g, "")
    .replace(/,([}\]])/g, "$1")
    .replace(/"(\w+)":/g, "$1:");

if (check) {
  if (normalise(readFileSync(outPath, "utf8")) !== normalise(source)) {
    console.error(`${outPath} is out of date: run node scripts/generate-deploy-artifacts.ts`);
    process.exit(1);
  }
  console.log("deployArtifacts.ts matches the Foundry build");
} else {
  writeFileSync(outPath, source);
  console.log(`wrote ${outPath} (format it with prettier)`);
}
