// Writes contracts/baseSepoliaContracts.ts from the Foundry build and the Base Sepolia record
// (contracts/deploy/base-sepolia.json, or ARL_SEPOLIA_RECORD): every ARL contract the app uses on
// Base Sepolia, with its ABI and the block it was deployed in (history reads start there).
//
//   node scripts/generate-sepolia-contracts.ts [--check]
//
// --check compares instead of writing, and fails if the committed file is out of date.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsDir = join(here, "..", "..", "..", "contracts");
const check = process.argv.includes("--check");
const recordPath =
  process.env.ARL_SEPOLIA_RECORD ?? join(contractsDir, "deploy", "base-sepolia.json");
const outPath = join(here, "..", "contracts", "baseSepoliaContracts.ts");

const NAMES = [
  "ARLAnonymousSignal",
  "ARLToken",
  "ARLVestingWallet",
  "ARLStakingRewards",
  "ARLJobs",
] as const;

const abi = (name: string): unknown =>
  (
    JSON.parse(readFileSync(join(contractsDir, "out", `${name}.sol`, `${name}.json`), "utf8")) as {
      abi: unknown;
    }
  ).abi;

function normalise(text: string): string {
  return text
    .replace(/\s+/g, "")
    .replace(/,([}\]])/g, "$1")
    .replace(/"(\w+)":/g, "$1:");
}

let body = "{}";
if (existsSync(recordPath)) {
  const record = JSON.parse(readFileSync(recordPath, "utf8")) as {
    chainId: number;
    contracts: Record<string, { address: string; deployedOnBlock: number }>;
  };
  if (record.chainId !== 84_532) throw new Error(`${recordPath} is not a Base Sepolia record`);
  const contracts = Object.fromEntries(
    NAMES.map((name) => {
      const c = record.contracts[name];
      if (!c) throw new Error(`${recordPath} has no ${name}`);
      return [name, { address: c.address, abi: abi(name), deployedOnBlock: c.deployedOnBlock }];
    }),
  );
  body = `{\n  84532: ${JSON.stringify(contracts, null, 2).replace(/\n/g, "\n  ")},\n}`;
}

const source = `/**
 * Generated by scripts/generate-sepolia-contracts.ts from the Foundry build and the Base Sepolia
 * record (contracts/deploy/base-sepolia.json). Do not edit by hand. Empty until the Base Sepolia
 * ecosystem is recorded.
 */
const baseSepoliaContracts = ${body} as const;

export default baseSepoliaContracts;
`;
if (check) {
  if (normalise(readFileSync(outPath, "utf8")) !== normalise(source)) {
    console.error(`${outPath} is out of date: run node scripts/generate-sepolia-contracts.ts`);
    process.exit(1);
  }
  console.log("baseSepoliaContracts.ts matches the Base Sepolia record");
} else {
  writeFileSync(outPath, source);
  console.log(`wrote ${outPath} (format it with prettier)`);
}
