/**
 * Generated by scripts/generate-sepolia-contracts.ts from the Foundry build and the Base Sepolia
 * record (contracts/deploy/base-sepolia.json). Do not edit by hand. Empty until the Base Sepolia
 * ecosystem is recorded.
 */
const baseSepoliaContracts = {} as const;

export default baseSepoliaContracts;
