/**
 * Generated by scripts/generate-deploy-artifacts.ts from the Foundry build. Do not edit by hand.
 */
export const DEPLOY_ARTIFACTS = {
  ARLVestingWallet: {
    creationHash: "0xec33acfaaeb7a7eeec179484b0b7e26f649feca2ebe45ad2d7e56e53c809b1ca",
    creationSize: 2857,
    constructorInputs: [
      {
        name: "beneficiary",
        type: "address",
        internalType: "address",
      },
      {
        name: "cliffStart_",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "cliffEnd_",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "vestingEnd_",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  ARLTimelock: {
    creationHash: "0x7ebd1071cb25c96daf20bbcf5c524c0946d38d49511ff775081d86f5e0f81356",
    creationSize: 7938,
    constructorInputs: [
      {
        name: "minDelay",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "proposers",
        type: "address[]",
        internalType: "address[]",
      },
      {
        name: "executors",
        type: "address[]",
        internalType: "address[]",
      },
      {
        name: "guardian",
        type: "address",
        internalType: "address",
      },
    ],
  },
  ARLToken: {
    creationHash: "0xe45878e1c9fca3c5b5450898e5ebf53ee2574d19c80c0011ac8acbabd6fcb0b1",
    creationSize: 5911,
    constructorInputs: [
      {
        name: "r",
        type: "tuple",
        internalType: "struct ARLToken.Recipients",
        components: [
          {
            name: "publicLaunch",
            type: "address",
            internalType: "address",
          },
          {
            name: "communityStaking",
            type: "address",
            internalType: "address",
          },
          {
            name: "ecosystemGrowth",
            type: "address",
            internalType: "address",
          },
          {
            name: "strategicPartnerships",
            type: "address",
            internalType: "address",
          },
          {
            name: "liquidity",
            type: "address",
            internalType: "address",
          },
          {
            name: "founder",
            type: "address",
            internalType: "address",
          },
          {
            name: "investors",
            type: "address",
            internalType: "address",
          },
          {
            name: "treasury",
            type: "address",
            internalType: "address",
          },
          {
            name: "team",
            type: "address",
            internalType: "address",
          },
          {
            name: "earlyUsers",
            type: "address",
            internalType: "address",
          },
          {
            name: "grantsBugBounty",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
  },
} as const;
