// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.36;

/// @notice The zero-knowledge verifier generated by Barretenberg (bb 5.2.0) for the ARL anonymous
/// signal circuit (zk/semaphore).
interface IARLSignalVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external
        view
        returns (bool);
}

/// @title ARL anonymous signals
/// @notice Members of a group signal (vote, attest, give feedback) without revealing which member
/// they are, at most once per scope. Membership is proven with a zero-knowledge proof against the
/// group's Merkle root; the proof also yields a nullifier that is the same for a member every time
/// they signal in a scope, and the contract accepts each nullifier once.
///
/// The protocol follows Semaphore. The proof checks (current or recently replaced root, unused
/// nullifier, scope and message hashed into the field, public input order) are adapted from
/// SemaphoreNoir.sol (github.com/hashcloak/semaphore-noir, packages/contracts-noir, commit
/// 6e24a48b2cb22c05a0c13361b5228d5e1c99bd0d, MIT, Copyright (c) 2025 Ethereum Foundation).
/// ARL changes: the group's membership tree is kept off-chain and only its root is published by
/// the group admin, a fixed circuit depth (16) and one verifier, and no upgrade or owner role.
///
/// Roles: each group has an admin, who publishes its root and can hand the role on or renounce it.
/// The admin cannot signal for members, read identities or reuse a nullifier.
contract ARLAnonymousSignal {
    /// @notice BN254 scalar field order; roots and nullifiers are field elements.
    uint256 public constant SNARK_FIELD =
        21_888_242_871_839_275_222_246_405_745_257_275_088_548_364_400_416_034_343_698_204_186_575_808_495_617;

    /// @notice How long a replaced root still accepts proofs, so members proving against the
    /// previous root are not cut off by an update.
    uint256 public constant ROOT_GRACE_PERIOD = 1 hours;

    IARLSignalVerifier public immutable verifier;

    struct Group {
        address admin;
        uint256 root;
        mapping(uint256 root => uint256 replacedAt) replacedRoots;
        mapping(uint256 nullifier => bool) nullifiers;
    }

    uint256 public groupCount;
    mapping(uint256 groupId => Group) private _groups;

    event GroupCreated(uint256 indexed groupId, address indexed admin, uint256 root);
    event MembersAdded(uint256 indexed groupId, uint256[] commitments);
    event RootUpdated(uint256 indexed groupId, uint256 previousRoot, uint256 root);
    event AdminChanged(
        uint256 indexed groupId, address indexed previousAdmin, address indexed admin
    );
    event Signal(
        uint256 indexed groupId,
        uint256 indexed scope,
        uint256 message,
        uint256 nullifier,
        uint256 root
    );

    error SignalZeroAddress();
    error SignalInvalidRoot();
    error SignalInvalidCommitment(uint256 commitment);
    error SignalNoGroup(uint256 groupId);
    error SignalNotAdmin(uint256 groupId);
    error SignalUnknownRoot(uint256 root);
    error SignalRootExpired(uint256 root);
    error SignalNullifierUsed(uint256 nullifier);
    error SignalInvalidProof();

    constructor(IARLSignalVerifier verifier_) {
        if (address(verifier_) == address(0)) revert SignalZeroAddress();
        verifier = verifier_;
    }

    modifier onlyAdmin(uint256 groupId) {
        if (_groups[groupId].admin != msg.sender) revert SignalNotAdmin(groupId);
        _;
    }

    // ---------------------------------------------------------------- groups

    /// @notice Creates a group whose members are published: `commitments` are emitted (see
    /// addMembers) and `root` is the root of the tree built from them, in order.
    function createGroupWithMembers(uint256[] calldata commitments, uint256 root)
        external
        returns (uint256 groupId)
    {
        _checkCommitments(commitments);
        groupId = _createGroup(root);
        emit MembersAdded(groupId, commitments);
    }

    /// @notice Creates a group with the caller as admin and `root` as its membership root.
    function createGroup(uint256 root) external returns (uint256 groupId) {
        groupId = _createGroup(root);
    }

    function _createGroup(uint256 root) private returns (uint256 groupId) {
        _checkRoot(root);
        groupId = groupCount++;
        Group storage g = _groups[groupId];
        g.admin = msg.sender;
        g.root = root;
        emit GroupCreated(groupId, msg.sender, root);
    }

    /// @notice Publishes a new membership root. The previous root keeps working for
    /// ROOT_GRACE_PERIOD.
    function updateRoot(uint256 groupId, uint256 root) external onlyAdmin(groupId) {
        _updateRoot(groupId, root);
    }

    /// @notice Adds members and publishes the resulting root. The commitments are emitted so
    /// that anyone can rebuild the tree (members need it to prove) and check it against the
    /// root; the contract does not hash the tree itself.
    function addMembers(uint256 groupId, uint256[] calldata commitments, uint256 root)
        external
        onlyAdmin(groupId)
    {
        _checkCommitments(commitments);
        emit MembersAdded(groupId, commitments);
        _updateRoot(groupId, root);
    }

    function _updateRoot(uint256 groupId, uint256 root) private {
        _checkRoot(root);
        Group storage g = _groups[groupId];
        uint256 previous = g.root;
        if (root == previous) revert SignalInvalidRoot();
        g.replacedRoots[previous] = block.timestamp;
        // A root that becomes current again is no longer a replaced one.
        delete g.replacedRoots[root];
        g.root = root;
        emit RootUpdated(groupId, previous, root);
    }

    /// @notice Hands the admin role to `admin`; address(0) renounces it and freezes the root.
    function changeAdmin(uint256 groupId, address admin) external onlyAdmin(groupId) {
        _groups[groupId].admin = admin;
        emit AdminChanged(groupId, msg.sender, admin);
    }

    // ---------------------------------------------------------------- signals

    /// @notice Records `message` in `scope` from an anonymous member of `groupId`.
    /// @param root The membership root the proof was made against (current, or replaced within
    /// ROOT_GRACE_PERIOD).
    /// @param nullifier The proof's nullifier; each is accepted once per group.
    function signal(
        uint256 groupId,
        uint256 scope,
        uint256 message,
        uint256 root,
        uint256 nullifier,
        bytes calldata proof
    ) external {
        Group storage g = _groups[groupId];
        if (groupId >= groupCount) revert SignalNoGroup(groupId);
        if (root != g.root) {
            uint256 replacedAt = g.replacedRoots[root];
            if (replacedAt == 0) revert SignalUnknownRoot(root);
            // slither-disable-next-line timestamp
            if (block.timestamp > replacedAt + ROOT_GRACE_PERIOD) revert SignalRootExpired(root);
        }
        if (g.nullifiers[nullifier]) revert SignalNullifierUsed(nullifier);

        bytes32[] memory publicInputs = new bytes32[](4);
        publicInputs[0] = bytes32(hashToField(scope));
        publicInputs[1] = bytes32(hashToField(message));
        publicInputs[2] = bytes32(root);
        publicInputs[3] = bytes32(nullifier);
        if (!verifier.verify(proof, publicInputs)) revert SignalInvalidProof();

        g.nullifiers[nullifier] = true;
        emit Signal(groupId, scope, message, nullifier, root);
    }

    // ---------------------------------------------------------------- views

    function groupAdmin(uint256 groupId) external view returns (address) {
        return _groups[groupId].admin;
    }

    function groupRoot(uint256 groupId) external view returns (uint256) {
        return _groups[groupId].root;
    }

    function isNullifierUsed(uint256 groupId, uint256 nullifier) external view returns (bool) {
        return _groups[groupId].nullifiers[nullifier];
    }

    /// @notice Maps a uint256 into the field, as the prover does (Semaphore convention).
    function hashToField(uint256 value) public pure returns (uint256) {
        return uint256(keccak256(abi.encodePacked(value))) >> 8;
    }

    function _checkCommitments(uint256[] calldata commitments) private pure {
        for (uint256 i; i < commitments.length; ++i) {
            if (commitments[i] == 0 || commitments[i] >= SNARK_FIELD) {
                revert SignalInvalidCommitment(commitments[i]);
            }
        }
    }

    function _checkRoot(uint256 root) private pure {
        if (root == 0 || root >= SNARK_FIELD) revert SignalInvalidRoot();
    }
}
